from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import BlogTag, Blog
from .serializers import BlogTagSerializer, BlogSerializer, BlogListSerializer
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework import generics
from rest_framework.generics import ListAPIView
from rest_framework.pagination import PageNumberPagination
from user.models import UserAuth
from common.views import CustomJWTAuthentication, IsAdminUser, IsAdminUser
from common.constants import S3_BLOG_BUCKET_NAME
from common.utils.s3_utils import delete_image_from_s3, upload_image_to_s3
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.exceptions import PermissionDenied


class BlogTagListCreateView(APIView):
    authentication_classes = [CustomJWTAuthentication]  # or your custom class

    def get_permissions(self):
        if self.request.method == 'GET':
            return [AllowAny()]
        return [IsAdminUser()]

    def get(self, request):
        tags = BlogTag.objects.all()
        serializer = BlogTagSerializer(tags, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = BlogTagSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()  # slug will be auto-generated by model save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

class BlogTagDetailView(generics.DestroyAPIView):
    queryset = BlogTag.objects.all()
    serializer_class = BlogTagSerializer
    authentication_classes = [CustomJWTAuthentication]

    def get_permissions(self):
        if self.request.method == 'DELETE':
            return [IsAdminUser()]
        return [AllowAny()]


class BlogListCreateAPIView(APIView):
    authentication_classes = [CustomJWTAuthentication]
    permission_classes = [IsAdminUser]

    def get(self, request):
        staff_param = request.query_params.get("staff")
        print("blog list create staff_param:", staff_param)
        blogs = None
        if staff_param is not None:
            if staff_param.lower() == "true":
                blogs = Blog.objects.filter(user__is_staff=True).defer('content').order_by('-created_at')
            elif staff_param.lower() == "false":
                blogs = Blog.objects.filter(user__is_staff=False).defer('content').order_by('-created_at')
            else:
                return Response(
                    {"error": "Invalid value for 'staff' parameter. Use 'true' or 'false'."},
                    status=status.HTTP_400_BAD_REQUEST
                )
        else:
            blogs = Blog.objects.all().defer('content').order_by('-created_at')

        # blogs = Blog.objects.all().defer('content').order_by('-created_at')
        serializer = BlogSerializer(blogs, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        user = request.user
        serializer = BlogSerializer(data=request.data, context={'request': request})
        is_published = request.data.get("is_published") in ["true", "True", True]
        if serializer.is_valid():
            try:
                custom_user = UserAuth.objects.get(id=user.id)
            except UserAuth.DoesNotExist:
                return Response({"Error": "User not found in UserAuth."}, status=400)

            # get display name depending on profile type
            if hasattr(user, 'profile'):
                author_name = user.profile.name
            elif hasattr(user, 'admin_profile'):
                author_name = user.admin_profile.full_name
            else:
                author_name = 'Unknown'

            # print("Auth Type from Token:", getattr(user, 'auth_type_from_token', 'N/A'))

            serializer.save(user=custom_user, author=author_name, is_published=is_published)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class BlogDetailAPIView(APIView):
    authentication_classes = [CustomJWTAuthentication]
    permission_classes = [IsAdminUser]

    def get_object(self, pk):
        return get_object_or_404(Blog, pk=pk)

    def get(self, request, pk):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog)
        return Response(serializer.data)

    def put(self, request, pk):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog, data=request.data, context={'request': request})
        is_published = request.data.get("is_published") in ["true", "True", True]
        if serializer.is_valid():
            serializer.save(is_published=is_published)
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        blog = self.get_object(pk)
        blog.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class PublishedBlogPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 50

class PublishedBlogListAPIView(generics.ListAPIView):
    queryset = Blog.objects.filter(is_published=True).order_by('-created_at')
    serializer_class = BlogListSerializer
    pagination_class = PublishedBlogPagination
    permission_classes = [AllowAny]

class PublishedBlogDetailAPIView(generics.RetrieveAPIView):
    queryset = Blog.objects.filter(is_published=True)
    serializer_class = BlogSerializer  # ✅ Includes content
    permission_classes = [AllowAny]


# user blogs
class UserBlogListCreateAPIView(APIView):
    authentication_classes = [CustomJWTAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        blogs = Blog.objects.filter(user=user).defer('content').order_by('-created_at')
        serializer = BlogSerializer(blogs, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        user = request.user
        serializer = BlogSerializer(data=request.data, context={'request': request})
        is_published = request.data.get("is_published") in ["true", "True", True]
        if serializer.is_valid():
            try:
                custom_user = UserAuth.objects.get(id=user.id)
            except UserAuth.DoesNotExist:
                return Response({"Error": "User not found in UserAuth."}, status=400)

            # get display name depending on profile type
            if hasattr(user, 'profile'):
                author_name = user.profile.name
            elif hasattr(user, 'admin_profile'):
                author_name = user.admin_profile.full_name
            else:
                author_name = 'Unknown'

            # print("Auth Type from Token:", getattr(user, 'auth_type_from_token', 'N/A'))

            serializer.save(user=custom_user, author=author_name, is_published=is_published)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserBlogDetailAPIView(APIView):
    authentication_classes = [CustomJWTAuthentication]
    permission_classes = [IsAuthenticated]

    def get_object(self, pk):
        blog = get_object_or_404(Blog, pk=pk)
        if blog.user != self.request.user:
            raise PermissionDenied("You do not have permission to access this blog.")
        return blog

    def get(self, request, pk):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog)
        return Response(serializer.data)

    def put(self, request, pk):
        blog = self.get_object(pk)
        serializer = BlogSerializer(blog, data=request.data, context={'request': request})
        is_published = request.data.get("is_published") in ["true", "True", True]
        if serializer.is_valid():
            serializer.save(is_published=is_published)
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        blog = self.get_object(pk)
        blog.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


# S3 image manager
class S3ImageManager(APIView):
    parser_classes = (MultiPartParser, FormParser)
    authentication_classes = [CustomJWTAuthentication]
    permission_classes = [IsAuthenticated]
    # permission_classes = [AllowAny]

    def post(self, request):
        """
        Upload an image to a folder.
        Example: POST with 'image' in form-data, optional 'folder'
        """
        image_file = request.FILES.get('image')
        folder = request.data.get('folder', 'cover')

        if not image_file:
            return Response({'error': 'No image file provided'}, status=400)

        bucket = S3_BLOG_BUCKET_NAME
        response = upload_image_to_s3(image_file=image_file, folder=folder, bucket=bucket)

        if not response['error']:
            print('Response message:', response['message'], 'url:', response['url'])
            return Response({'message': response['message'], 'url': response['url'], 'key': response['key']}, status=200)
        
        if response['error']:
            print('Response error message:', response['message'])
            return Response({'message': response['message']}, status=400)
        

    def delete(self, request):
        """
        Delete an image from S3.
        Example: DELETE /api/s3-image/?key=cover/image.jpg
        """
        image_key = request.query_params.get('key')

        if not image_key:
            return Response({'error': 'Image key is required'}, status=400)

        bucket = S3_BLOG_BUCKET_NAME

        response = delete_image_from_s3(bucket=bucket, image_key=image_key)

        if not response['error']:
            print('Response message:', response['message'], image_key)
            return Response({'message':response['message']}, status=200)
        
        if response['error']:
            print('Response error message:', response['message'])
            return Response({'message':response['message']}, status=400)




import boto3
from django.conf import settings
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework import status

# @api_view(['GET'])
# @permission_classes([AllowAny])
# def get_image_url(request):
#     image_key=request.query_params.get('key')
#     bucket=S3_BLOG_BUCKET_NAME

#     if not image_key:
#         return {'error': 'Image key is required', 'success': False}

#     response = get_image_url(bucket=bucket, image_key=image_key)

#     if not response['error']:
#         print('Response message:', response['message'])
#         return Response({'message':response['message']}, status=200)
    
#     if response['error']:
#         print('Response error message:', response['message'])
#         return Response({'message':response['message']}, status=400)



class ListS3Images(APIView):
    permission_classes = [AllowAny]  # Just for testing

    def get(self, request):
        folder = request.query_params.get('folder', 'cover/')  # default to 'cover/' folder

        s3 = boto3.client(
            's3',
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            region_name=settings.AWS_S3_REGION_NAME
        )

        bucket_name = settings.AWS_STORAGE_BUCKET_NAME

        try:
            response = s3.list_objects_v2(Bucket=bucket_name, Prefix=folder)
            files = []

            for obj in response.get('Contents', []):
                key = obj['Key']
                # Skip folders
                if not key.endswith('/'):
                    file_url = f"https://{bucket_name}.s3.amazonaws.com/{key}"
                    files.append(file_url)

            return Response({"images": files})
        except Exception as e:
            return Response({"error": str(e)}, status=500)
        