AUTH_TYPE_GOOGLE='GOOGLE'
AUTH_TYPE_EMAIL='EMAIL'
AUTH_TYPE_ADMIN='ADMIN'
AUTH_TYPE_USER='USER'

S3_BLOG_BUCKET_NAME="worthminds-blogs"
S3_MAGAZINE_BUCKET_NAME="worthminds-magazines"
S3_CONTRIBUTORS_BUCKET_NAME="worthminds-contributors"